### ISSUE TITLE
Moving a choice that's inside a loop raises an error

### ISSUE THREAD

**Issue by nesadrian** [equinor/MAD-VSM-WEB#687] opened 2024-02-12 13:14 UTC
**To Reproduce**

1. Go to a process
2. Add a choice card
3. Add a sub activity card beneath one of the choices children
4. Merge the new sub activity with the choice card
5. Try to move the choice card
6. See error

**Expected behavior**
The choice should be movable even though it's in a loop.

**Screenshots**
![image](https://github.com/equinor/flyt/assets/35768833/8a1ecd2e-e51f-4977-aa58-f3910e7f60f5)

**Comment by QiJin-Bouvet** [comment] 2024-02-19 13:40
#688 is a duplicate of this issue.
Will test both scenarios when this issue is fixed.

**Comment by nesadrian** [comment] 2024-02-19 14:33
@QiJin-Bouvet Ready for test in POC DEV/QA. I discovered a new issue while working on this. If you move a choice that's inside a loop to another main activity column then it will still have the merge connection to the top of the loop. I will create a new issue for this.

**Comment by QiJin-Bouvet** [comment] 2024-02-20 10:45
Tested in qa-graph-poc.
The choice card in loop is movable. But still merge to the previous tree. This will be fixed in another card #???

**Comment by nesadrian** [comment] 2024-02-21 09:10
@QiJin-Bouvet A new. issue has been made here #690

**Closed as completed** 2024-04-29 13:08 UTC
Labels: bug, front-end
