### ISSUE TITLE
 Versioning

### ISSUE THREAD

**Issue by askbulle** [equinor/MAD-VSM-WEB#154] opened 2021-09-09 11:38 UTC
**User input**
In addition to general metadata, also a version history with author would be useful (when sharing function with edit is available).

**Sharepoint ID(s)**
31

**User story**
As an end-user I want to keep track of all changes and possibly being able to roll-back to earlier versions to be able to understand history and secure understanding for where we are today and why (continuous improvement).

---

![image](https://user-images.githubusercontent.com/3164065/142992325-d8a7d19b-1876-4fcd-a201-6eb83ad04410.png)

## Back-end requirements
- [x] New route to retrieve the times when a project changed
- [x] New parameter to Project/GetById for "as of datetime x"
~- [ ] Any more routes that need to support "as of"?~ Potentially the vsmObject detail view... but we can manage without.

## User Requirements (for testing)
Unless mentioned otherwise, any user can do the following:

**Current**
- [ ] User can see the current version.
- [ ] User (with edit-role) can edit a card in the current version.
- [ ] User can see the details of any card in the current version.

**Previous**
- [ ] User can see a list of all versions by clicking on the version icon (down right-hand corner). (versions are ordered by date and only one per day is shown)
- [ ] User can switch between showing the changes grouped by Year, Month, Day, Hours, Minutes or Seconds (default to Days)
- [ ] User can view a previous version.
- [ ] User can view the details of any card in a previous version.
- [ ] User can share the url of any version with others (copy from the url bar) and opening the url in a new tab will show that version, with the version view visible.
- [ ] User **_cannot_** edit a card in a previous version. ( Drag'n drop interactions should be disabled, and sidebar view should be in read-only mode. )
- [ ] Exiting the version view should return the user to the current version.
- [ ] Current and To be processes should work the same as expected.

**Comment by knudsvik** [comment] 2021-09-13 08:28
Should #192 be solved at the same time?

**Comment by SegarJJ** [comment] 2021-09-20 08:48
I was thinking this story could be split into two features.  to ease us into it.   One feature to view the changes on the VSM and another to allow the admin some method to start a rollback process, whatever it may include....

**Comment by Magos** [comment] 2021-09-24 06:22
After technical exploration with @pagodo we have some conclusions:

- The Temporal Tables feature of our database seem to be our best approach for this versioning feature, offering performance improvements over maintaining our own history tables with triggers.
- This should minimize the alterations to existing code for CRUD operations.
- In order to actually perform time travelling queries we have two options:
   - Drop down in abstraction to SQL instead of Entity Framework for these queries.
   - Update the API server to run on .Net 6, so we can access Entity Framework 6. Both of these technologies are currently considered **release candidates**, not finished releases.

**Comment by pagodo** [comment] 2021-09-24 07:25
Moving to a release candidate for the technology the api is based on is not a good idea, there is a good chance we will be left with a unstable system. The release of these versions is set to early november and we should at least wait with the prod release until the technology is formaly released and if we are to release a early version of dotnet6 we have to do extensive testing of the api. But we may do development targeting a release candidate

**Comment by SjoenH** [comment] 2021-09-27 07:16
Maybe we should put this on hold untill @Linedueo have landed on designing functionality requirements with our POs?

We may consider supporting the release-candidate only for Flyt application if we find that the new functionality it provides is the best way to implement our versioning -requirements.

**Comment by SjoenH** [comment] 2021-09-29 07:22
From Daily 29 sept:
It sounds like we probalbly should store all changes with timestamps in the back-end. (temporal tables etc)
Then it is a visualisation problem to pick good points. Or we could show them all like in Figma history view.

Talking with @Magos we believe that the view should be able to update quite quickly when selecting a prior state.

**Comment by Linedueo** [comment] 2021-09-29 10:47
Versjonshistorikken blir visualisert som en timeline. Denne viser en oversikt over datoer hvor prosessen har blitt endret (oppsummert per dag)

**Comment by SjoenH** [comment] 2021-09-30 04:48
Sounds good @Linedueo.
Please update user-story and notify us when it's ready for development.

**Comment by SjoenH** [comment] 2021-11-10 08:52
@Magos tells us that .Net6 is out! 🥳

**Comment by knudsvik** [comment] 2021-11-11 09:33
@SjoenH : New requirement for this feature. Update the delete/reset button explanatory texts, ref #192 . When a to-be process is reset, the version history will still keep the old version I guess.

**Comment by SjoenH** [comment] 2021-12-01 08:59
**API discussion.**
Changing `created` and `lastUpdated` to a date.
The `created` object is used today to check if we are an admin, thus `userAccesses` needs to include the admin as well. (remove filter)

**Remember:** We want all connected `vsmObjects` (`card`) and  `task` (`PQIR`) etc… -changes to be reflected in the `process`-changelog.

**Aggregating the changes to one day.**
Front-end or back-end? 🤔 
Are there any performance considerations here?

**Comment by SjoenH** [comment] 2021-12-06 08:36
@Magos @SjoenH Let's have a quick chat later today

**Comment by SjoenH** [comment] 2021-12-07 09:35
@Magos What you have done sounds good.

Aggregation is a front-end task as of now.

@Magos have looked at api-endpoint for process-changelog, but mentions that he could add endpoints for VSMObjects, and PQIR, but not implementing that at this time.

Let me know when it is ready for testing in Front-end. :smile:

**Comment by Magos** [comment] 2021-12-15 08:26
I just built a version to dev, which should fix these issues

- UserAccess DELETE is now handled by accessing the Accesses table, not the UserAccesses view.
- Task-category links changelogging now uses explicit db calls rather than assuming the entity has its project entity included
- Corrected the column name in the VsmUpdates db function.

**Comment by SjoenH** [comment] 2022-01-03 09:25
@Magos I'm back from my vacation now and will test your new build :muscle:

**Comment by SjoenH** [comment] 2022-01-03 13:56
@Magos. Some initial testing.

- [x] Update endpoint now returns an array dates. https://github.com/equinor/MAD-VSM-WEB/issues/154#issuecomment-990293902
- [x] Adding categories seems to work as expected. https://github.com/equinor/MAD-VSM-WEB/issues/154#issuecomment-990276498
- [x] Removing a user from a process works
- [ ] **But changing the role of a user gives error 500(?)**

**Error 500**
The entity type 'UserAccess' is not mapped to a table, therefore the entities cannot be persisted to the database. Call 'ToTable' in 'OnModelCreating' to map it to a table.

**Comment by Magos** [comment] 2022-01-04 13:52
Update-ruter som ikke fungerer pr nå:

- [ ] UserAccess
- [ ] Object

**Comment by SjoenH** [comment] 2022-01-04 14:15
Also, adding that there seems to be some issues with getting the process I want for a given date-time. `asOf` string not matching or something? Needs to be looked into.

**Comment by SjoenH** [comment] 2022-01-31 12:46
@Magos Do you have an update on where we are at with versioning?

**Comment by SjoenH** [comment] 2022-01-31 13:06
Had a talk with @Magos 

**Current status.** API is now ready for further front-end development. 

Updates should now be watched by the API and stored in history. So the issue I raised above should now be fixed.

**Comment by ntorsen** [comment] 2022-03-01 13:00
Looks good @SjoenH 👍

**Comment by SjoenH** [comment] 2022-03-04 14:02
@Magos I've released to Dev. Seems to work fine, except for selecting the first date. Could you help debug why that is? [Example process](https://web-vsm-dev.radix.equinor.com/process/825?version=2022-01-06T13%3A34%3A17.818Z)

**Comment by SjoenH** [comment] 2022-03-04 14:07
@ntorsen I want to remove the requirement - "_User cannot delete a previous version. The button should be disabled to not confuse users._" As it doesn't feel quite necessary... 🤔

**Comment by ntorsen** [comment] 2022-03-04 14:11
@SjoenH That's true. Sure, you can remove it 👍

**Comment by SjoenH** [comment] 2022-03-07 09:31
Update: API does not include Timezone information in the `/updates`-response. @Magos will take a look at adding it. 👍

**Comment by SjoenH** [comment] 2022-03-08 13:13
FYI. Ready in QA as well for some testing. 
This one is a bit hard to test well, since we need changes spanning a couple of days...

I've done that testing in Dev environment, so I'm pretty confident that it's ok, but you might discover something else. 😄  So super if you can start some light testing of this. 💪

**Comment by knudsvik** [comment] 2022-03-08 13:39
@SjoenH Created a process in QA, but it is not saved.. something's off.

**Comment by SjoenH** [comment] 2022-03-08 13:42
@knudsvik What number process?

@Magos could you help investigate? Also, seems like the sorting on the front-page is reversed...? Are we running the same in Test as in QA? 🤔

**Comment by knudsvik** [comment] 2022-03-08 13:43
Ahh, they are there, just reversed on the front page as you say

**Comment by SjoenH** [comment] 2022-03-08 13:44
Super 💪

**Comment by ntorsen** [comment] 2022-03-09 07:58
@Magos I get error 500 when I delete Questions and Ideas when testing. They do get deleted eventually, but this message pop up so it looks like it is having some problems. This is in Test environment. 
![image](https://user-images.githubusercontent.com/89014017/157397216-89e1d03f-b8f6-493f-b02e-aef03c70cc3c.png)

**Comment by Magos** [comment] 2022-03-09 10:40
I deployed a fix for the 500 error, but the Risk report seems to be correct as such. Could you have been pressing delete before the front-end had updated after a change?

**Comment by ntorsen** [comment] 2022-03-09 11:37
> I deployed a fix for the 500 error, but the Risk report seems to be correct as such. Could you have been pressing delete before the front-end had updated after a change?

Working good now @Magos 🤩
No trouble with Risk either, it could have been that I pressed deleted before front-end had updated after change.

**Comment by ntorsen** [comment] 2022-03-09 11:52
@SjoenH Tried out new solution and Flyt does not seem to like it when I go back to the start on Seconds (both for Current and To-be process). Message "ERROR: Project contains no root onjects" pops up. If I select other versions other than the first one this is not a problem. 
![image](https://user-images.githubusercontent.com/89014017/157436427-f64c2a88-649d-4ad8-a63e-727907b91647.png)

**Comment by SjoenH** [comment] 2022-03-10 06:34
@Magos is this something you want to improve? Looks like the first logged change in  `/updates` is created before the process is ready.

**Comment by SjoenH** [comment] 2022-03-10 09:14
@Magos To reproduce. Create a new process. Then the first returned timestamp in the `/updates` response does not exist.

**Comment by Magos** [comment] 2022-03-10 12:04
I've attempted a fix by returning the Update values instead of the PeriodStart values stored, but this is not late enough after the creation process to avoid making the version of the process without objects in it visible. At the moment, I'm inclined not to do more to hide this unless @knudsvik and @askbulle think it's important to hide.

**Comment by SjoenH** [comment] 2022-03-14 09:16
Todo:
- [ ] Remove second-resolution selection.

**Comment by SjoenH** [comment] 2022-03-14 09:47
I've removed the second resolution and released to QA again. @ntorsen Would you please do a final test of everything before we plan the release?

**Comment by ntorsen** [comment] 2022-03-14 10:55
@SjoenH here are some feedback from testing done in **QA environment.**
User requirements for testing ✔
Second-resolution selection is removed ✔
Deleting PQIRs is working as expected ✔

Other remarks:
- If you copy the URL of a previous version and opening it in a new window, you will see that that version is visible. However, when looking at cards for more info a "invalid process type" message pops up as well as a 500 internal server error. This does not happen for all cards, but in this case it happened on a blue and yellow card. 
![image](https://user-images.githubusercontent.com/89014017/158156837-2d9e386e-36dd-4bc9-b9e3-8b4e169edf21.png)

- Going back in time (to the start) when selecting Minute-resolution selection, same message as for Second-resolution comes up:
![image](https://user-images.githubusercontent.com/89014017/158155912-480b6d73-02cc-4190-9eae-521d20787c7d.png)

**Comment by SjoenH** [comment] 2022-03-14 11:23
@ntorsen can you reproduce the error with a new process?

**Comment by SjoenH** [comment] 2022-03-14 11:24
@ntorsen I'll look into the 500 errors.

**Comment by ntorsen** [comment] 2022-03-14 11:43
@SjoenH able to recreate it by deleting a card --> navigate back to when it existed --> copy URL into a new window (incognito) --> clicking on deleted card to view it 
![image](https://user-images.githubusercontent.com/89014017/158165290-75c23199-d028-4f04-8330-1d9d761060cb.png)

**Comment by SjoenH** [comment] 2022-03-14 12:34
@ntorsen fix is out in QA again. 🧪

**Comment by ntorsen** [comment] 2022-03-14 12:50
Working good now 🏆 @SjoenH

**Closed** 2022-03-15 09:20 UTC
Labels: enhancement, feedback

**Comment by SjoenH** [comment] 2022-03-16 09:08
⏳ 🚀 @knudsvik @askbulle 
We have some changes that requires downtime. We are planning to release at 11:45.
Estimated downtime up to 1 hour.

-----
@Magos 
- [ ] Database. Schema changes. Activate system-versioning (or whatever it is called...) 
- [ ] Code
+ Some changes related to solving tasks.

Frontend
Push out what's in QA and bump version + change-log.
