### ISSUE TITLE
Copy current process to the To-Be process

### ISSUE THREAD

**Issue by knudsvik** [equinor/MAD-VSM-WEB#363] opened 2022-02-02 13:42 UTC
**User input**
Would it be possible to automatically update the To Be with the same process, but with the ability to delete what has been improved or even gray out?  I like the As-Is and To-Be feature that was added, but anything to reduce typing the steps again and visually showing what has changed would be awesome.

**User**
Jenny Fried

**Sharepoint ID**
128

Relates to 

- #314
-

**Comment by knudsvik** [comment] 2022-02-02 13:44
Same as #314

**Comment by knudsvik** [comment] 2022-04-04 13:00
Suggest to add a "Import current" button here:
![image](https://user-images.githubusercontent.com/25986427/161549074-b19275e6-be80-455c-950c-7a9f314b941d.png)

**Comment by askbulle** [comment] 2022-04-04 13:00
@SjoenH @dansvend Quick fix?

**Comment by askbulle** [comment] 2022-04-04 13:06
Closing due to Duplicate of #314

**Closed by askbulle** 2022-04-04 13:06 UTC
Labels: enhancement, feedback
