### ISSUE TITLE
New feedback - ID 

### ISSUE THREAD

**Issue by knudsvik** [equinor/MAD-VSM-WEB#367] opened 2022-02-10 18:55 UTC
**User input**
Just an idea as we continue to love the tool!  Sometimes we  have files or screenshots of what we want to improve.  Maybe it would be great if you could add an image?  If not, I could probably put in TEAMS and then add a link? 

**Sharepoint list ID**
130

**User**
Jenny Fried

**Comment by askbulle** [comment] 2022-03-28 10:53
Duplicate of #170

**Closed by askbulle** 2022-03-28 10:53 UTC
