### ISSUE TITLE
Marking PQI as Solved

### ISSUE THREAD

**Issue by knudsvik** [equinor/MAD-VSM-WEB#165] opened 2021-09-09 12:10 UTC
**User input 1**
Possibility to mark problems, ideas and questions as solved. Now it's only possible to delete them (not desirable as it is part of the meta-data needed).

**User input 2**
When a problem is deleted from a flow, it still is registered as an "existing problem" and still appears in "categorize PQIR's"

**Sharepoint ID(s)**
49, 105

**Requirements (for @ntorsen)**
- [x] Checkbox next to problem or risk with hover text "Solve" or "Mitigate", respectively.
- [x] Problem or risk disappear from canvas when marked as solved.
- [x] Problem or risk are placed under section "Solved or mitigated" in the card side sheet, and are grayed out.
- [x] Description of solved problem or risk is visible.
- [x] Checkbox next to solved problem or riks with hover text "Unsolve" or "Unmitigate"? (@Linedueo can you confirm the use of these two words?)
- [x] Solved PQIR's should not show in the categorisation page.

**Comment by Linedueo** [comment] 2021-11-01 09:15
![Skjermbilde 2021-11-01 kl  10 12 05](https://user-images.githubusercontent.com/74361011/139648979-1394e850-bb52-4f1e-ab15-b681c2e1ecf1.png)

@knudsvik @SjoenH 
Checkbox to mark as solved is placed under trash button. There will be a tooltip to explain. A snackbar will appear after marking as solved to be able to undo. Marked problem or risk will now be hidden from canvas. When clicking on an idea or question the checkbox will be disabled.

**Comment by Linedueo** [comment] 2021-11-01 09:15
Figma 👉🏻 https://www.figma.com/file/IkHwmIQrsT0iR34f5R5UnZ/VSM?node-id=2970%3A114316

**Comment by knudsvik** [comment] 2021-11-01 09:44
@Linedueo Check if an updated design to show the solved stuff also should include these improvements: #158

**Comment by SjoenH** [comment] 2021-11-01 09:44
What happens in the categorization page?

**Comment by Linedueo** [comment] 2021-11-15 07:08
I have looked at what we talked about during the meeting last week. Solved or mitigated problems/risks will be listed under and grayed out to show they are disabled. 

<img width="1252" alt="Skjermbilde 2021-11-15 kl  08 03 29" src="https://user-images.githubusercontent.com/74361011/141736791-c6183c29-6bd5-4e58-95d0-9ce943e1a15d.png">

Figma link 👉🏻 https://www.figma.com/file/IkHwmIQrsT0iR34f5R5UnZ/VSM?node-id=2970%3A114316

**Comment by Linedueo** [comment] 2021-11-15 07:09
@SjoenH @knudsvik ☝🏻

**Comment by knudsvik** [comment] 2021-11-15 07:49
Looks good 👍

**Comment by SjoenH** [comment] 2021-11-15 08:37
Looks good, but missing some design regarding interacting with solved PQIRS.
Unsolve etc...
I guess we can use the same section box for that? @Linedueo

**Comment by Linedueo** [comment] 2021-11-23 08:24
![Skjermbilde 2021-11-23 kl  09 18 23](https://user-images.githubusercontent.com/74361011/142990156-9b7d23d3-536a-47ff-907b-f61b9e7fb2cf.png)

Whatever is solved is listed below. In case you want to unsolve you´ll have a section box just like the one above to be able to read and unsolve (uncheck) if necessary and the problem will go back to the section above. @SjoenH I followed your suggestion- made more sense to use the same component. Let me know if anything is unclear!

Figma 👉🏻 https://www.figma.com/file/IkHwmIQrsT0iR34f5R5UnZ/VSM?node-id=3005%3A116534

**Comment by martabenthem** [comment] 2021-11-24 07:48
Will start up on this one. 

@Linedueo thank you for the design, for now everything is clear. Did we decide what happens to the solved problem in the categorisation page?

**Comment by Linedueo** [comment] 2021-11-24 08:19
<img width="451" alt="Skjermbilde 2021-11-24 kl  09 18 37" src="https://user-images.githubusercontent.com/74361011/143200626-b266ba9c-1ed8-4e45-be14-06205000652e.png">

Updated with solve or mitigate and unsolve or unmitigate

**Comment by Linedueo** [comment] 2021-11-24 08:20
<img width="533" alt="Skjermbilde 2021-11-24 kl  09 20 33" src="https://user-images.githubusercontent.com/74361011/143200898-3a4e625b-aba8-426d-8141-ed26e6b75ac0.png">

Updated with solve or mitigate and unsolve or unmitigate

**Comment by SjoenH** [comment] 2021-11-24 08:28
@Linedueo Why do you want a snack-bar here?

**Comment by SjoenH** [comment] 2021-11-24 08:39
Bringing this to your attention again... @Linedueo @knudsvik @askbulle What happens in the categorization page?

**Comment by SjoenH** [comment] 2022-01-10 10:32
We also talked about and decided that we don't need two text-areas. The important is to separate the solved or mitigated PQIRS from the unsolved ones.

**Comment by SjoenH** [comment] 2022-01-10 13:48
@knudsvik @askbulle 👋 
Do we need to differentiate between a solved PQIR by itself and a solved PQIR on a card?

The Implementation I've done now is on the PQIR level. That means, when I mark a PQIR as solved, it will be solved and removed from all of the places in the process.

**Comment by SjoenH** [comment] 2022-01-10 14:07
@knudsvik @askbulle 
Here's a video to further explain how it works as of now.
https://user-images.githubusercontent.com/3164065/148778952-caed281f-e56d-4b84-8f91-215b889c0f2e.mp4

You may give it a try in Test environment https://web-vsm-test.radix.equinor.com

Let me know if this is as we expect it to work or if we need to do some adjustments. :grin:

**Comment by SjoenH** [comment] 2022-01-10 14:25
@ntorsen @Linedueo  Please do some testing.
I updated EDS library, so please have a look throughout and check if something looks off or doesn't work anymore :sweat_smile:

**Comment by ntorsen** [comment] 2022-01-11 10:27
### **Results from testing environment**
_Tested in Edge and Chrome_

**What is working good:**
- Checkbox displays hover text for all PQIRs, both when unsolved and solved ("Mark as solved"/"Mark as unsolved", "Mark as approved"/"Mark as declined", etc.)
- PQIRs disappear from canvas when solved (as well as existing PQIRs)
- PQIRs are greyed out when solved, and a description text is visible
- Solved PQIRs does not show on the categorisation page 
- If putting a category on PQIR on the categorisation page first, and then setting PQIR as solved, they will not show on page
- If marking PQIRs as unsolved and going back to the categorisation page, they will get categories again (that was dragged on the PQIRs before they got solved)
- There is no mixing with PQIRs from current or to-be process, they keep to their own page (this goes for categorisation page and PQIRs as well)

**Remarks**
- @knudsvik mentioned in Process labels that when searching for a label by standing in the writing field then it wants to purpose stuff that has already been written. This happens also when renaming a process and when searching for username or title on landing page:

_(Chrome)_
![image](https://user-images.githubusercontent.com/89014017/148924025-10f26690-35c3-4aa5-bd09-3c79a2092587.png)

![image](https://user-images.githubusercontent.com/89014017/148924072-1a336495-b918-456d-bfea-41b20ca23551.png)

_(Edge)_
![image](https://user-images.githubusercontent.com/89014017/148924327-74df1ff8-48d2-40ae-afdc-0dbdd486d4ad.png)
In Edge there is an option to delete element

- If you go and delete a PQIR the hover text will show "Delete selected QIP". Maybe include R here as well?
![image](https://user-images.githubusercontent.com/89014017/148925330-948c89ef-da61-415c-b679-21ea61565a27.png)

**Comment by ntorsen** [comment] 2022-01-11 10:30
Forgot to tag @SjoenH ☝

**Comment by knudsvik** [comment] 2022-01-11 12:31
@SjoenH 

1. Comment in this thread from October 18th: 
> This is only needed for problems and risks, i.e. questions and ideas should still only have the delete functionality. Hover-over-text:
> - Problems: Solved
> - Risks: Mitigated

2. When it comes to the question above: When checking off the problem or risk it should only be removed from the activity card the user has open, not for all the cards where it exists. We could add another step in the future: if problem exist several places then ask user if to solve only here or in all activities - not MVP though.

3. Another thing we noticed in the test: When marking a P as problem it is not possible to unceck it without clicking somewhere else first

4. When adding an existing problem which is already solved it should be "unsolved" at that activity.

**Comment by SjoenH** [comment] 2022-01-11 12:41
@knudsvik Thanks for the feedback and testing. 2. Solving at the “card-level” and not at the PQIR-level needs some changes to the API… not currently supported.

I'm removing the `Quick-fix` label

@Magos PING! Let's have a chat about this.

@ntorsen Thanks for testing. Browser suggestions should only be disabled for fields where it is affecting the user experience negatively.

**Comment by SjoenH** [comment] 2022-01-19 11:54
@Magos I cannot get the solve task endpoint to work. Please give me a call so we can figure it out.

**Comment by SjoenH** [comment] 2022-01-20 10:48
Update, Solving tasks is now working in Dev and Test environment, but API returns wrong solved-status on the categories-page. @Magos will fix that and report back when it is ready to test.

**Comment by Magos** [comment] 2022-01-24 09:46
Finally it seems like the deploy issues are cleared up. Task solving is now available to test on environments dev and test.

**Comment by SjoenH** [comment] 2022-01-24 11:15
Seems to be working good @Magos :clap: 

I'll disable the check-box for Questions and Ideas. (only needed for problems and risks)

@knudsvik Since we are not solving Questions and Ideas, should they be hidden from the categorization page if they are not assigned to any cards?

**Comment by SjoenH** [comment] 2022-01-24 12:18
@ntorsen Ready for testing in **DEV ENVIRONMENT** https://web-vsm-dev.radix.equinor.com/

**Comment by knudsvik** [comment] 2022-01-24 12:39
> @knudsvik Since we are not solving Questions and Ideas, should they be hidden from the categorization page if they are not assigned to any cards?

@SjoenH You touch on something we haven't really thought through here. I think the solution here is to think of this feature as a MVP in the canvas page only and not changing anything on the categorisation page but describe and solve that in a separate issue...

**Comment by ntorsen** [comment] 2022-01-24 15:40
### Test in DEV environment
**Working good 💪
Results from testing:**
- Question and Idea does not have checkboxes anymore. Only checkboxes for when solving tasks for Problem and Risk
- Checkbox displays hover text for PR, Problem="Mark as solved" and Risk="Mark as mitigated"
- When checked, Problem displays hover text "Mark as unsolved" and Risk="Mark as unmitigated"
- PRs disappear from canvas on that activity card when solved. When checking off the PR it only gets removed from the activity card the user has open, not for all the cards where it exists
- PRs are greyed out when solved, and a description text is visible
- Solved PRs does not show on the categorisation page

⚠When deleting a QIPR, the hover text still says "Delete selected QIP". RIsk is not included. 
This has been mentioned before above, but mentioning it again 🙂

@SjoenH @Magos

**Comment by SjoenH** [comment] 2022-01-24 20:13
@ntorsen thanks for thorough testing.

I've now updated hover-text for deling to account for the PQIR type. Ready in dev environment

**Comment by ntorsen** [comment] 2022-01-25 08:20
This is looking good now too 💪

**Comment by SjoenH** [comment] 2022-01-25 09:06
@knudsvik @askbulle Ready for testing in QA.
https://web-vsm-qa.radix.equinor.com/process/166

**Comment by knudsvik** [comment] 2022-01-25 14:09
@SjoenH Nothing happens when I solve a problem, doesn't seem like it's working...

**Comment by SjoenH** [comment] 2022-01-25 14:56
I'm sorry. We forgot to release the API... :eyes: 
We just released the update, but it seems to have some issues. @Magos can you take a look at this? :thinking: 
![image](https://user-images.githubusercontent.com/3164065/151000506-cbe31760-9516-4ff9-a64c-6c14b5145a88.png)

Reproduce by creating/opening a process.

**Comment by Magos** [comment] 2022-01-27 11:42
I've run a database migration and redeployed the backend now. Testing should be available again (test and qa environments).

**Comment by SjoenH** [comment] 2022-01-31 12:48
Got it! Moving it back to QA.

@knudsvik @askbulle Ready for testing in QA.
https://web-vsm-qa.radix.equinor.com/process/166

**Comment by SjoenH** [comment] 2022-02-01 09:36
Approved for release.

**Closed** 2022-02-08 14:38 UTC
Labels: enhancement, feedback, question, back-end
