### ISSUE TITLE
Links in an activity card

### ISSUE THREAD

**Issue by knudsvik** [equinor/MAD-VSM-WEB#317] opened 2021-12-01 08:51 UTC
**User input**
Include possibility for link in card - yellow (and blue) cards. Can i.e. have a link to ARIS or to a checklist.

**Sharepoint list ID**
107

**User**
Liv Håøy

**Comment by SjoenH** [comment] 2021-12-01 13:19
Duplicate of #189

**Comment by knudsvik** [comment] 2021-12-03 12:58
Related also to
- #175 
- #301

**Closed** 2022-02-09 07:18 UTC
Labels: enhancement, feedback
