### ISSUE TITLE
Links not url's

### ISSUE THREAD

**Issue by knudsvik** [equinor/MAD-VSM-WEB#175] opened 2021-09-09 12:25 UTC
**Users**
Thorjan Knudsvik, Fredrik Liknes x2, Liv Håøy

**User input (ID 78)**
Insert links on words, not the full url, to save space in activity boxes.

**User input (ID 102)**
Add functionality to link in URLs in Problems/ideas/risks etc.. Then you can refer further if you have an idea you want to share a link to for further work.

**User input (ID 107)**
Include possibility for link in card - yellow (and blue) cards. Can i.e. have a link to ARIS or to a checklist.

**User input 4 (ID137)**
As a user I would like to be able to add hyperlinks to the flow elements to make them "cleaner" than they are by adding URLs to the boxes.

**Sharepoint ID**
78, 102, 107, 137

-- 
## Design
https://user-images.githubusercontent.com/74361011/149290585-ae33248a-e61b-4074-88b8-835bbaa159fe.mov

## Requirements (for testing)

- [x] User can insert links wherever there is a text field
- [x] Links open in a new tab
- [x] Marking text and clicking on the link icon should bring up a popup where the user can enter the `link`.
- [x] The URL should automatically add the `https://` to the URL if it doesn't exist.
- [x] Marking text and pressing `CTRL+K` should do the same thing
- [x] Cards on the canvas should display the `display-text` of the `link`, and not the full URL
- [x] Links should be clickable in the detail-view of a card, but not in the Canvas card.
- [ ] ~~User can remove a link by removing the display text~~
- [x] Hover over the link icon should display a tool-tip with the text "Insert link"
- [ ] ~~Hover over a link should display a tool-tip with "`Open http://...your link here...`" , so that the user knows where the link goes.~~
- [x] A user cannot add an invalid URL. (simple validation)
- [x] Show an error If an invalid URL is provided.

**Comment by SjoenH** [comment] 2021-09-27 09:22
Markdown formatting could be the solution here. Needs to do some changes to the sidesheet. 
- View & edit modes.
- Consider Replace input to markdown formatter ( since users generally don't know markdown)... ++

**Comment by Linedueo** [comment] 2022-01-13 08:08
Har satt opp en skisse her på hvordan en bruker lett kan legge på en link i stedet for å kopiere inn lange url´s.
@SjoenH @knudsvik 

https://user-images.githubusercontent.com/74361011/149290585-ae33248a-e61b-4074-88b8-835bbaa159fe.mov

**Comment by knudsvik** [comment] 2022-01-13 09:14
Looks good @Linedueo. Would be nice if a word (or several words) could be marked and then clicking on the url icon for pre-filled text in the popup. Also CTRL+K shortcut!

**Comment by knudsvik** [comment] 2022-01-13 11:19
This feature will be good to have in place before #157

**Comment by knudsvik** [comment] 2022-01-14 07:39
@SjoenH The link features should be available also in PQIR's and all type of cards. Is this a big feature?

**Comment by SjoenH** [comment] 2022-01-14 08:18
All our text is stored as strings in our DB.
So I'm thinking that markdown is well suited for adding formatting markup to our text.

There already exists libraries for this, but I'm not sure how easy it is to get the EDS-style as Line provided. 
I'll need to look into this. Potentially making something custom.

The EDS-look will most likely be what takes the most time to implement.

**Comment by SjoenH** [comment] 2022-01-26 19:08
:wave: @Linedueo 
I don't see why we need the `linked text` input. I'm considering dropping it.

**Comment by Linedueo** [comment] 2022-01-26 20:43
@SjoenH Totally agree!

**Comment by SjoenH** [comment] 2022-03-15 11:05
I think creating our own markdown editor with the same styling as above might be too much work for this feature.
So I suggest at least trying something quicker and simpler...

- [ ]  1. use @uiw/react-md-editor to render a markdown editor. [Example for next.js](https://www.npmjs.com/package/@uiw/react-md-editor#support-nextjs)
- [ ] 2. disable everything except links in the editor.
- [ ] 3. When the user opens a card, the text-input should be opened in a view-mode. (Thus displaying the links with proper styling)
- [ ] 4. Clicking on the text-field (or an edit-button) switches it to edit-mode.
- [ ] 5. You should be able to exit the edit mode. (might need a button for this...)
- [ ] 6. Filter away markdown link metadata from the text for use in cards on the canvas.

**Comment by SjoenH** [comment] 2022-03-16 08:50
@dansvend talk with @Linedueo if you have any questions. Try to update this task with what you decide on. Thank you 🙏

**Comment by dansvend** [comment] 2022-03-21 09:57
Me, @SjoenH and @Linedueo just had a meeting about the design of this feature. We will try out this feature using the npm-package [@uiw/react-md-editor](https://github.com/uiwjs/react-md-editor).

The design will be as follows:
1. Display the markdown preview in the right hand side panel after clicking on a VSM object.
2. Display an edit button to change to the split view of the markdown editor making you able to add links to text.
3. Display a checkmark button to switch back to preview mode.

**Comment by dansvend** [comment] 2022-03-22 09:09
@Linedueo Do you have a design for this? 😊

**Comment by Linedueo** [comment] 2022-03-22 10:21
<img width="1330" alt="Skjermbilde 2022-03-22 kl  11 20 05" src="https://user-images.githubusercontent.com/74361011/159458975-b2a212ae-baa3-4d4c-87cc-2218601ab086.png">

@dansvend jeg har lagt inn edit ikon og satt størrelsen på sidesheet til XL.

**Comment by SjoenH** [comment] 2022-03-24 09:03
Todo @dansvend 

- [ ] Change SideSheet width to `640px`

- [ ] Implement changes that @Linedueo  will report

- [ ] Polish  💅

**Comment by Linedueo** [comment] 2022-03-24 11:03
@dansvend @SjoenH I´ve come to the conclusion that the edit icon should just stay where it is (inside the text field) that is how the component is set up and it makes more sense to have it be a part of that.

**Comment by dansvend** [comment] 2022-03-25 07:59
Sounds good 👌  Thanks for taking a look at this @Linedueo 😊

**Comment by ntorsen** [comment] 2022-03-28 11:41
@dansvend is this ready for testing?

**Comment by dansvend** [comment] 2022-03-28 12:39
@ntorsen Not yet. I moved the card a little too fast 🚀  I need to fix one thing before Henry can approve it. Will send you a message when it's ready 😊

**Comment by dansvend** [comment] 2022-03-29 10:22
@askbulle @knudsvik @Linedueo @ntorsen This has now been released to the test environment. Please test this when you have some time. Thanks🙏

**Comment by knudsvik** [comment] 2022-03-30 06:37
@dansvend
Hi, I think the markdown links setup could work, but it needs some refinement, as I think it was unecessary complex for the users in the current state.
- Extra click to go into edit mode :( Could this be replaced by clicking in the text box instead? Clicking outside of it again could  confirm changes.
- Did not like the split edit mode, both for complexity and for the wider side panel.
- If the link does not start with `http:\\` the link will translated to `https://web-vsm-test.radix.equinor.com/process/nrk.no`
- I think it's ok to open external links in another tab, but internal links (to other processes) could possibly be opened in same tab (need to keep in mind consistency here as well).
- It's not possible to see on the canvas that there is a link on the card, and not possible to click it either.
- I liked the little top bar which probably can be extended with other formatting options later? Like Bold, Italic, bullet lists etc?
- Very good that CTRL+K is working too.
- One of the process cards in [this process](https://web-vsm-test.radix.equinor.com/process/445) did not format the link properly on the canvas.
- Other markdown stuff works as well, i.e. `# Heading 1` and `**bold**` and is showing in the sidebar, but not on the canvas. Could be interesting to explore further

**Comment by dansvend** [comment] 2022-03-30 08:03
@knudsvik Thanks for you thorough testing and great feedback 🙏 

I am not working on Flyt for the rest of the week but I will take this feedback into consideration and try to make a better solution🛠

**Comment by Linedueo** [comment] 2022-03-30 08:04
@dansvend @knudsvik

- I think that we should click directly on the box to edit- the check button is ok I think!
- Remove the split edit mode and instead open a new dialog box when clicking on "add new link" where the user insert det link.
- Be able to see link on a card by using underline on text.

**Comment by SjoenH** [comment] 2022-04-04 08:34
Todo @dansvend 
- [ ] Underline the link on canvas. (But still black text.)
- [ ] Links should not be clickable on the cards in the canvas.
- [ ] No dialog box on insert. ( let's try the cheap way first )
- [ ] Remove split view.

**Comment by dansvend** [comment] 2022-04-06 11:38
@askbulle @knudsvik @Linedueo @ntorsen The things in the above checklist have been implemented for this feature and are ready to be tested in the QA-environment. The links are not marked on the canvas cards currently as they seem hard to implement. We can do it in a cheap way now with just adding underscore or asterisks before and after the link. It would look like this: 

`Visit _Equinor_ for more details`
or
`Visit *Equinor* for more details`

What do you think of this?

**Comment by askbulle** [comment] 2022-04-06 12:10
jojo[hepp](goodshit.org)

**Comment by knudsvik** [comment] 2022-04-06 12:36
### Results from QA
Me and @askbulle has tested now, very nice @dansvend!, almost there! A few last adjustments:

- [ ] Marking a word and clicking CTRL+K or the URL icon sets the marked area on the url text, not the url itself, so not possible to just press CTRL+V afterwards without marking the url part. `[this area is now marked](url)` - `[text](this area should be marked)`
- [ ] Still, providing a URL without `http://`, e.g. `nrk.no` will be translated to `https://web-vsm-qa.radix.equinor.com/process/nrk.no`
- [ ] The width of the sidebar is wider than before, please keep same as in prod
- [ ] The font size in the Description box is smaller than in Role, Problems etc

When it comes to indicating a link in the canvas, just drop it for now, we'll get back to that later.

**Comment by dansvend** [comment] 2022-04-21 08:11
Hi @Linedueo  😊

Which do you prefer for adding a link; a scrim taking up the whole screen or this solution which is similar to what is used for QIPR's?
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/47424077/164409552-6ba5c97b-e22f-4341-8063-33800be5d96c.png">

**Comment by SjoenH** [comment] 2022-04-21 08:40
@dansvend I think your suggestion looks nice. 👍 
I agree that it's smart to keep the same UX.

So unless @Linedueo has any objections, I say go for it 💪

**Comment by Linedueo** [comment] 2022-04-21 09:25
@dansvend I don´t have any objections- go for it! :) Your suggestion looks good!

**Comment by dansvend** [comment] 2022-04-21 11:35
@knudsvik @askbulle @ntorsen @Linedueo 
New version released to test and QA environments🚀

Appreciate if you can take some time to test it and give feedback 🙏 

FYI: It seems like the text gets duplicated if you're adding a link while using grammarly browser extension. Don't know if we should look into this atm

**Comment by knudsvik** [comment] 2022-04-22 07:13
@dansvend I don't get this, why has this feature now suddenly changed from the last QA? We did not have a requirement of opening a link form (probably not the right term) when inserting a link, and it wasn't there on the last round of QA..

Findings:

- [ ] When marking a word and clicking CTRL+K, Internet Explorer opens the URL bar in addition to the new link form. 
- [ ] Not sure I like the new link form, why do we need it? It will not be consistent if adding other markdown formatting options (bold, italics etc). 
- [ ] When clicking on a link already present, a new window opens, but the Description box is put in to markdown mode (for processes I have write access to).

![image](https://user-images.githubusercontent.com/25986427/164623915-52f0c7af-b9ab-4395-972c-a78ef9032814.png)

**Comment by dansvend** [comment] 2022-04-25 08:31
@knudsvik 

Thanks for giving feedback. As discussed in meeting 25th April we agreed on the following:

- Keep the "Add link"-form

Fix the following:

- [ ] Fix ctrl + k in Microsoft Edge
- [ ] Remove placeholder text `equinor.com` on "Add link"-form

**Comment by dansvend** [comment] 2022-04-25 09:54
@knudsvik 

A new version is ready for testing and is available in both Test- and QA environments 🚀 

- `ctrl` + `k` should now work as expected
- Placeholder text on the `Link`-input field in the `Add link`-form has been removed

**Comment by knudsvik** [comment] 2022-04-25 10:04
@dansvend Superb! Ready for release :) 

Just a quick check: I hope the cards will not look like this in prod after release? (missing modified, users etc)
![image](https://user-images.githubusercontent.com/25986427/165067804-1ad57305-80db-4eaa-9679-96a1d716fe3c.png)

**Comment by dansvend** [comment] 2022-04-25 10:15
@knudsvik Perfect! Thanks for rapid response 💪 

We will make sure this is fixed before releasing. This feature was started when the missing modifiers, users etc was in the main branch but it will be fixed when merging the feature branch into the main branch.

@ntorsen This feature is ready for testing 🧪

**Comment by ntorsen** [comment] 2022-04-25 12:18
@dansvend I've tested in Test environment (on browser Edge and Chrome). Working really good 💪
All the requirements for testing passed ✅

I found a small thing when testing (not critical and should not impact release, but worth mentioning..) If you add a link and confirm it by clicking on the check mark, URL-text appear right away in sidebar and everything works good. 
![image](https://user-images.githubusercontent.com/89014017/165085632-3120f5e7-134b-4614-805e-8e9635d7854f.png)

But if you add a link and then (without using the check mark) click outside the sidebar, you will see the URL-text on the card, however, not when you click the card to see more details. The description field will be empty. So if you write something directly in there after opening it, it will overwrite the URL. A workaround was to open card, click outside sidebar again, and click card again. The second time it appears in other words (and working as intended). 
![image](https://user-images.githubusercontent.com/89014017/165087378-722a2018-cac2-40f1-903a-68a2015b66d4.png)

**Comment by dansvend** [comment] 2022-04-25 12:27
@ntorsen Thanks for testing this and giving great feedback 🙏 

The problems your mentioning is that the description text in the sidepanel is cached and you therefore have to click out of it and in again to make react query fetch the data again. This bug was not introduced in this feature but is the same in production today as well. However, I actually created an issue for this exact bug earlier today so it should get fixed. I also found it confusing. The issue for this bug can be found here #411 

I'm moving this card to "Pending release" 🚦

**Comment by dansvend** [comment] 2022-05-05 13:31
@askbulle @knudsvik @ntorsen
This is ready for testing in Test and QA environments after refactor 🧪
It should work the same as during last test, but you might find a bug before it gets released 🚀

**Comment by knudsvik** [comment] 2022-05-05 19:26
@dansvend me and @askbulle have tested. Looks good to us 🦾

**Comment by ntorsen** [comment] 2022-05-06 07:13
@dansvend Working good when testing for me as well🏆

**Comment by dansvend** [comment] 2022-05-06 07:28
@askbulle @knudsvik @ntorsen 
Thanks for taking your time to test this 🙏 Then we're ready to release this 🚀

**Closed** 2022-05-06 12:32 UTC
Labels: enhancement, feedback, front-end
